- src/app.module.ts
app module에 수정한 사항이 이전 커밋에서 빼먹어서 추가합니다
> Feat: 마이그레이션 app.module 로직 추가

- package-lock.json
- package.json
- src/app.module.ts
- src/config/typeorm.config.ts
typeorm.config을 추가했는데 여기에 .env에 DB정보를 넣어야 합니다
예시
POSTGRES_TYPE=postgres
POSTGRES_HOST=localhost
POSTGRES_PORT="55001"
POSTGRES_USERNAME=postgres
POSTGRES_PASSWORD=postgrespw
POSTGRES_DATABASE=postgres
> Fix: 네스트에서 DB를 인식할 수 있게 개선

- src/entities/admins.entity.ts
- src/entities/cadets.entity.ts
- src/entities/comments.entity.ts
- src/entities/keywords.entity.ts
- src/entities/mentor-keywords.entity.ts
- src/entities/mentoring-logs.entity.ts
- src/entities/mentors.entity.ts
- src/entities/reports.entity.ts
- tsconfig.json
Fix: deletedAt nullabe:true & tsconfig 15~17line false
> POL-9 -> feature PR

- src/entities/admins.entity.ts
- src/entities/cadets.entity.ts
- src/entities/comments.entity.ts
- src/entities/keywords.entity.ts
- src/entities/mentoring-logs.entity.ts
- src/entities/mentors.entity.ts
- src/entities/reports.entity.ts
> HOTFIX-POL-9 -> feature PR

- package-lock.json
- package.json
- src/config/typeorm.config.ts
- src/entities/admins.entity.ts
- src/entities/cadets.entity.ts
- src/entities/mentor-keywords.entity.ts
- src/entities/reports.entity.ts
Fix: 엔티티 카멜케이스와 스네이크케이스 충돌문제 해결 및 엔티티 이름 오류 수정
PR이 완료되면 feature 브랜치에서 git pull 후 아래 링크 참고
https://42polar.atlassian.net/wiki/spaces/P/pages/786517
database의 column 이름만 스네이크케이스로 바뀌었을뿐 typeorm 코드 작성시 카멜케이스로 작성가능
> POL-26 -> feature PR

- src/entities/mentors.entity.ts
- src/entities/reports.entity.ts
Fix: 엔티티 이름 오류 수정
mentors.entity.ts -> availableTime
reports.entity.ts -> mentoringLogs
> POL-26 -> feature

- src/v1/config/typeorm.config.ts
- src/v1/dto/keywords/create-keyword.dto.ts
- src/v1/dto/keywords/delete-keyword.dto.ts
- src/v1/entities/keywords.entity.ts
- src/v1/keywords/keywords.controller.ts
- src/v1/keywords/keywords.module.ts
- src/v1/keywords/service/keywords.service.ts
Fix: Get 권한 수정 및 Post & Delete 메서드 주석처리
> POL-1 -> feature PR

- src/v1/cadets/service/cadets.service.ts
- src/v1/dto/cadet-mentoring-logs.interface.ts
- src/v1/mentors/service/mentors.service.ts
> Feat: 예외처리, 키값 intra -> intraId 변경

- src/v1/dto/cadets/create-apply.dto.ts
> Pol 3 fix: dto create-apply

- package-lock.json
- package.json
- src/data-source.ts
- src/v1/seeds/admins.seeder.ts
- src/v1/seeds/cadets.seeder.ts
- src/v1/seeds/comments.seeder.ts
- src/v1/seeds/keywords.seeder.ts
- src/v1/seeds/main.seeder.ts
- src/v1/seeds/mentor-keywords.seeder.ts
- src/v1/seeds/mentors.seeder.ts
- src/v1/seeds/reports.seeder.ts
seeding 구현했습니다.
테스트 해보았을 때 성공했습니다.
아직 fake data(랜덤으로 user생성)저장을 구현 못했지만, **데이터 저장하는게 빨리 필요할것같아서 우선 pr올립니다.**
> Pol 10 - seeding 데이터베이스 구현

- src/v1/cadets/apply/apply.service.ts
- src/v1/cadets/cadets.controller.ts
> Pol 3a Fix:apply

- package-lock.json
- package.json
- src/main.ts
- src/util/swagger.ts
> POL-77a Feat:swagger defalut

- src/v1/auth/auth.controller.ts
- src/v1/cadets/apply/apply.service.ts
- src/v1/cadets/cadets.controller.ts
- src/v1/comments/comments.controller.ts
- src/v1/dto/available-time.dto.ts
- src/v1/dto/cadets/create-apply.dto.ts
- src/v1/dto/mentors/join-mentor-dto.ts
- src/v1/dto/mentors/mentor-detail.dto.ts
- src/v1/mentors/service/mentors.service.ts
class name 대문자 수정 & 약간의 수정된 스웨그가 들어갔어용~
> POL-77알파 Fix:class name

- genToken.js
- package.json
script => `npm run token`
Test: Generate token
> Feat: Generate token

- src/v1/bocals/bocals.controller.ts
- src/v1/calendar/calendar.controller.ts
- src/v1/calendar/service/calendar.service.ts
- src/v1/mentors/mentors.controller.ts
- src/v1/v1.controller.ts
Fix: getAvailabeTimes null 값 가지고 있을때 빈 배열 리턴 및 swagger api 수정중
> Fix: getAvailabeTimes null 값 가지고 있을때 빈 배열 리턴 및 swagger api 수정중

- src/v1/bocals/bocals.controller.ts
- src/v1/bocals/service/bocals.service.ts
- src/v1/cadets/apply/apply.service.ts
- src/v1/cadets/cadets.controller.spec.ts
- src/v1/calendar/calendar.controller.ts
- src/v1/email-verifications/email-verification.controllers.ts
- src/v1/mentoring-logs/mentoring-logs.controller.ts
- src/v1/mentors/mentors.controller.ts
> Feat: swagger api 추가

- src/v1/seeder/seeds/keywordCategories.seeder.ts
- src/v1/seeder/seeds/keywords.seeder.ts
> Fix: ios -> iOS

- src/v1/entities/mentors.entity.ts
Fix: mentor entity email 널가능  변경
> Fix: mentor entity email 널가능  변경

- package-lock.json
- package.json
- src/v1/seeder/seeds/categories.seeder.ts
- src/v1/seeder/seeds/keywordCategories.seeder.ts
- src/v1/seeder/seeds/keywords.seeder.ts
- src/v1/seeder/seeds/main.seeder.ts
- src/v1/seeder/seeds/mentor-keywords.seeder.ts
- src/v1/seeder/seeds/mentors.seeder.ts
> Fix: 엑셀에서 데이터 읽어와서 시딩

- src/bull-queue/login-consumer.ts
- src/http-exception.filter.ts
- src/v1/auth/auth.controller.ts
- src/v1/auth/auth.service.ts
- src/v1/comments/service/comments.service.ts
- src/v1/reports/service/reports.service.ts
JWT 액세스 토큰 만료 시 401, roles guard는 403
> Fix: HTTP 상태코드 변경

- src/v1/categories/service/keywords.service.ts
- src/v1/mentors/mentors.controller.ts
- src/v1/mentors/mentors.module.ts
- src/v1/mentors/service/mentors.service.ts
> Feat: 멘토 키워드 수정

- src/v1/v1.module.ts
> Remove: validate info middleware

- src/v1/dto/mentors/join-mentor-dto.ts
- src/v1/dto/mentors/mentor-detail.dto.ts
- src/v1/interface/mentors/update-mentor.interface.ts
- src/v1/mentors/mentors.controller.ts
- src/v1/mentors/service/mentors.service.ts
멘토 join, update api에 회사/직급 정보 추가
> Feat: 멘토 필수정보 - 회사/직급 추가

- src/v1/auth/auth.controller.ts
> Fix: 공통과정 체크 로직 수정

- src/v1/bocals/service/bocals.service.ts
- src/v1/bocals/service/data-room.service.ts
- src/v1/dto/reports/report.dto.ts
- src/v1/dto/reports/update-report.dto.ts
- src/v1/entities/reports.entity.ts
- src/v1/interface/bocals/mentoring-excel-data.interface.ts
- src/v1/reports/service/reports.service.ts
> feat: 레포트에 참여 카뎃 수정 기능

- src/v1/reports/service/reports.service.ts
과거 로직에서 미팅앳 변경 후 제출완료하면 변경 전 미팅앳으로 비용 정산
report.mentoringLogs.meetingAt에 변경 적용 라인 추가
> !HOTFIX: 미팅앳 변경 적용
